[package]
name = "quickemu-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
notify = "6"
sysinfo = "0.30"
anyhow = "1"
thiserror = "1"
dirs = "5"
chrono = "0.4"
tracing = "0.1"
tracing-subscriber = "0.3"
which = "6"

# TUI dependencies
ratatui = "0.26"
crossterm = "0.27"

[target.'cfg(target_os = "linux")'.dependencies]
procfs = "0.16"

[profile.release]
lto = true
opt-level = 3
strip = true