# Docker Compose override for WASM development
# This file extends the base configuration with WASM-specific services
# Usage: docker compose -f docker-compose.qemu.yml -f docker-compose.override.yml up

services:
  # Development container for building WASM locally
  wasm-dev:
    image: rust:latest
    working_dir: /app/spice-client
    volumes:
      - ../..:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/spice-client/target
    command: |
      bash -c "
        apt-get update && apt-get install -y pkg-config libssl-dev curl git && \
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh && \
        rustup target add wasm32-unknown-unknown && \
        cd /app/spice-client && \
        wasm-pack build --target web --out-dir pkg --no-opt && \
        echo 'WASM build complete! Files in pkg/'
      "
    networks:
      - spice-test

  # Simple HTTP server for testing WASM build
  wasm-server:
    image: python:3.11-alpine
    working_dir: /app
    volumes:
      - ../pkg:/app/pkg:ro
      - ../docker/index.html:/app/index.html:ro
    ports:
      - "8000:8000"
    command: python -m http.server 8000
    networks:
      - spice-test
    profiles:
      - wasm

volumes:
  cargo-cache:
  target-cache:

