services:
  # WASM build and serve container
  spice-client-wasm:
    build:
      context: ../..  # Build from project root
      dockerfile: spice-client/docker/Dockerfile.wasm
      cache_from:
        - rust:latest
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "8888:80"  # Serve on localhost:8888
    volumes:
      # Mount source for live development (optional)
      - ../src:/app/spice-client/src:ro
      - ../Cargo.toml:/app/spice-client/Cargo.toml:ro
    environment:
      - RUST_LOG=debug
    networks:
      - spice-test
    depends_on:
      - qemu-spice  # Can connect to the QEMU instance

  # Optional: Include the QEMU SPICE server from the other compose file
  qemu-spice:
    extends:
      file: docker-compose.qemu.yml
      service: qemu-spice
    networks:
      - spice-test

  # WebSocket proxy to bridge between WASM client and SPICE TCP server
  websocket-proxy:
    build:
      context: .
      dockerfile: Dockerfile.websocket-proxy
    ports:
      - "5959:5959"  # WebSocket proxy port
    networks:
      - spice-test
    depends_on:
      - qemu-spice

volumes:
  qemu-data:

networks:
  spice-test:
    driver: bridge