version: '3.8'

services:
  # SPICE Debug Test Server from spice-master
  spice-debug-test-server:
    build:
      context: ../spice-master
      dockerfile: Dockerfile.spice-debug-test
    image: spice-debug-test-server:latest
    container_name: spice-debug-test-e2e
    ports:
      - "5912:5912"
    environment:
      # Server configuration
      - SPICE_PORT=5912
      - SPICE_NO_AUTH=1
      # Enable all debug output
      - SPICE_DEBUG=1
      - G_MESSAGES_DEBUG=all
    volumes:
      # Packet captures
      - ./captures:/tmp/captures
      # Server logs
      - ./logs:/tmp/logs
    networks:
      - spice-test
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5912"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    # Log all output for debugging
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  # Native SPICE test client
  spice-test-client:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test-client
    image: spice-test-client
    container_name: spice-test-client-e2e
    depends_on:
      spice-debug-test-server:
        condition: service_healthy
    environment:
      - RUST_LOG=trace
      - SPICE_HOST=spice-debug-test-server
      - SPICE_PORT=5912
    networks:
      - spice-test
    volumes:
      # Share captures directory for analysis
      - ./captures:/captures
    command: ["/app/spice-test-client", "--host", "spice-debug-test-server", "--port", "5912", "--duration", "10", "-vv"]

networks:
  spice-test:
    driver: bridge