[application]
name = "Quickemu Manager"
asset_dir = "assets"
default_platform = "desktop"

[application.desktop]
out_dir = "dist"

[application.web]
out_dir = "dist"

[build]
cargo_args = ["--release"]

[[build.target]]
name = "x86_64-unknown-linux-gnu"

[[build.target]]
name = "x86_64-apple-darwin"

[[build.target]]
name = "aarch64-apple-darwin"


[bundle]
bundle_identifier = "com.quickemu.manager"
bundle_name = "Quickemu Manager"
bundle_version = "1.0.0"

[bundle.macos]
short_description = "Modern VM management application"
icon = ["assets/icon.icns"]
files = {}
hardened_runtime = true


[bundle.linux]
icon = ["assets/icon.png"]
categories = ["Utility", "System"]
files = {}