[application]
name = "quickemu-web"
default_platform = "web"

[web.app]
title = "Quickemu Manager"
base_path = "/"

[web.watcher]
reload_html = true
watch_path = ["src", "index.html"]

[web.resource.dev]

[bundle]
identifier = "org.quickemu.Manager"
publisher = "Quickemu"
icon = []
resources = []